chargen/urls.py
from django.urls import path

from . import views

app_name = "chargen"

urlpatterns = [
    path("random", views.create_character, name="create_character"),
]

dolmenwood/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("chargen", include("chargen.urls")),
]

chargen/models.py
from django.db import models

# Create your models here.

gamelogic/models.py
from django.db import models

# Create your models here.

chargen/views.py
from django.shortcuts import render
from .character import Character


def create_character(request):
    template_name = "chargen/create_character.html"
    context = {"char": Character}
    return render(request, template_name, context)

gamelogic/views.py
from django.shortcuts import render

# Create your views here.

chargen/templates/chargen/create_character.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Dolmenwood - Character Gen{% endblock title %}
{% block content %}
<h1>A Dolmenwood Character</h1>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{char.first_name}} {{char.last_name}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{char.background}}</h6>
    <p>{{char.profile|safe}}</p>
    <div class="row">
        <div class="col">
            <table class="table">
            <tr>
                <th>Strength</th>
                <th>Dexterity</th>
                <th>Constitution</th>
                <th>Intelligence</th>
                <th>Wisdom</th>
                <th>Charisma</th>
            </tr>
            <tr>
                <td>{{char.Strength}}</td>
                <td>{{char.Dexterity}}</td>
                <td>{{char.Constitution}}</td>
                <td>{{char.Intelligence}}</td>
                <td>{{char.Wisdom}}</td>
                <td>{{char.Charisma}}</td>
            </tr>
            <tr>
                <td>{{char.Strength_mod}}</td>
                <td>{{char.Dexterity_mod}}</td>
                <td>{{char.Constitution_mod}}</td>
                <td>{{char.Intelligence_mod}}</td>
                <td>{{char.Wisdom_mod}}</td>
                <td>{{char.Charisma_mod}}</td>
            </tr>
            </table>

        </div>

    </div><!-- row-->
  </div>
</div>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- boostrap CSS -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🧝‍♂️</text></svg>">

</head>

<body>
<header>

    {% block navbar %}


    <nav class="navbar navbar-expand-lg navbar-light bg-light">


    <!--new nav here-->
     <a class="navbar-brand" href="/">Dolmenwood</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Characters
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'chargen:create_character' %}">Create a random PC</a>
          <a class="dropdown-item" href="#">Choose background</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>


      <!--
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>

        <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>-->

    </ul>
  </div>
    </nav>

</header>

    {% endblock %}
    <main role="main" class="container">

    {% block messages %}
        {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
                {% endfor %}

        {% endif %}
    {% endblock %}

        {% block content %}{% endblock %}

    </main>

    <!-- Footer -->


    <!-- Footer -->
    <!-- Jquery and Popper-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Dolmenwood{% endblock title %}
{% block content %}
<h1>Welcome to the Dolmenwood GM assistant</h1>

<p>
Dolmenwood is a fantasy adventure game set in a lavishly detailed world inspired by the fairy tales and eerie folklore of the British Isles. Like traditional fairy tales, Dolmenwood blends the dark and whimsical, the wondrous and weird.</p>

<p>Players journey through tangled woods and mossy bowers, forage for magical mushrooms and herbs, discover rune-carved standing stones and hidden fairy roads, venture into fungal grottoes and forsaken ruins, battle oozing monstrosities, haggle with goblin merchants, and drink tea with fairies.</p>

<p>Streamlined rules and helpful introductory materials guide novice players, while unique new magic and monsters bring a fresh sense of the unknown to veteran role-players.</p>

<p>This tool is developped independently from the game, and is provided "as is".</p>
{% endblock content %}